def pltimg():
    from projectMarks import Marks
    from experienceMarks import expmarks
    from skillmarks import skMarks
    import matplotlib.pyplot as plt
    import os
    comapny,job,exp,lvl=expmarks()
    skillsnames,skillshave,skillpoints,allskillpoints=skMarks()
    exp_sum=sum(lvl)
    if exp_sum>3:
        exp_sum=3
    lab=["skilled","unskilled"]
    global percentage_exp
    percentage_exp=f"{(exp_sum/3)*100 :.2f}%"
    pr,lb,lv=Marks()
    plt.figure(figsize=(15,20))
    plt.subplot(7,3,1)
    plt.bar(job,lvl)
    plt.title("Experience")
    plt.yticks([1,2,3,4],["good","very good","excellent",""])
    plt.subplot(7,3,2)
    plt.bar(pr,lv)
    plt.title("Projects")
    plt.yticks([1,2,3,4,5,6],["beginner","intermediate","advance","expert","innovator",""])
    plt.subplot(7,3,3)
    plt.pie(skillpoints)
    plt.legend(skillshave,loc="right",bbox_to_anchor=(-0.2,1))
    plt.title("Overall Skill")
    plt.subplot(7,3,4)
    plt.pie(allskillpoints[0])
    plt.title(skillsnames[0])
    plt.legend(lab,loc="right",bbox_to_anchor=(-0.2,1)) 
    plt.subplot(7,3,5)
    plt.pie(allskillpoints[1])
    plt.title(skillsnames[1])
    plt.legend(lab,loc="right",bbox_to_anchor=(-0.2,1))    
    plt.subplot(7,3,6)
    plt.pie(allskillpoints[2])
    plt.title(skillsnames[2])
    plt.legend(lab,loc="right",bbox_to_anchor=(-0.2,1))    
    plt.subplot(7,3,7)
    plt.pie(allskillpoints[3])
    plt.title(skillsnames[3])
    plt.legend(lab,loc="right",bbox_to_anchor=(-0.2,1))    
    plt.subplot(7,3,8)
    plt.pie(allskillpoints[4])
    plt.title(skillsnames[4])
    plt.legend(lab,loc="right",bbox_to_anchor=(-0.2,1))  
    plt.subplot(7,3,9)
    plt.pie(allskillpoints[5])
    plt.title(skillsnames[5])
    plt.legend(lab,loc="right",bbox_to_anchor=(-0.2,1))  
    plt.subplot(7,3,10)
    plt.pie(allskillpoints[6])
    plt.title(skillsnames[6])
    plt.legend(lab,loc="right",bbox_to_anchor=(-0.2,1))  
    plt.subplot(7,3,11)
    plt.pie(allskillpoints[7])
    plt.title(skillsnames[7])
    plt.legend(lab,loc="right",bbox_to_anchor=(-0.2,1))  
    plt.subplot(7,3,12)
    plt.pie(allskillpoints[8])
    plt.title(skillsnames[8])
    plt.legend(lab,loc="right",bbox_to_anchor=(-0.2,1))  
    plt.subplot(7,3,13)
    plt.pie(allskillpoints[9])
    plt.title(skillsnames[9])
    plt.legend(lab,loc="right",bbox_to_anchor=(-0.2,1))  
    plt.subplot(7,3,14)
    plt.pie(allskillpoints[10])
    plt.title(skillsnames[10])
    plt.legend(lab,loc="right",bbox_to_anchor=(-0.2,1))
    plt.subplot(7,3,15)
    plt.pie(allskillpoints[11])
    plt.title(skillsnames[11])
    plt.legend(lab,loc="right",bbox_to_anchor=(-0.2,1)) 
    plt.subplot(7,3,16)
    plt.pie(allskillpoints[12])
    plt.title(skillsnames[12])
    plt.legend(lab,loc="right",bbox_to_anchor=(-0.2,1))  
    plt.subplot(7,3,17)
    plt.pie(allskillpoints[13])
    plt.title(skillsnames[13])
    plt.legend(lab,loc="right",bbox_to_anchor=(-0.2,1))   
    path=os.path.join("static","plots","firsts.png")
    plt.tight_layout()
    plt.savefig(path)
    plt.close()
    print("done")
    return percentage_exp,path